name: Publish on NPM
on:
    push:
        branches: [release]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 9
            - uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'pnpm'
            - run: pnpm install
            - run: pnpm prettier-check
            - run: pnpm build
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
